### ISSUE TITLE
braintree clientToken issue

### ISSUE THREAD

**Issue by kthomas80** [amejiarosario/meanshop#15]
When running the application and accessing the "checkout" page I receive this error:

/server/api/braintree/braintree.controller.js:33
    return handleResponse(res)(err, data.clientToken);
                                        ^
TypeError: Cannot read property 'clientToken' of null
    at /Applications/Sites/Tutorials/meanshop-book/server/api/braintree/braintree.controller.js:33:41
    at /Applications/Sites/Tutorials/meanshop-book/node_modules/braintree/lib/braintree/client_token_gateway.js:68:16
    at IncomingMessage.<anonymous> (/Applications/Sites/Tutorials/meanshop-book/node_modules/braintree/lib/braintree/http.js:99:18)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)

**Comment by kthomas80** [comment]
disregard, i figured it out ... I had the public/private/merchant id in the wrong order.
